name: build
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  Run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install shellcheck
        run: sudo apt-get -y install shellcheck
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run shellcheck
        run: shellcheck *.sh
